services:
  kpd-backend:
    build: backend/
    image: kupipodaridai-backend
    container_name: kpd-backend-cont
    depends_on:
      - postgres
    ports: 
      - "4000:3000"
    links:
      - postgres:$POSTGRES_HOST
    env_file:
      - .env
    restart: on-failure
  postgres:
    image: "postgres"
    container_name: kpd-db-cont
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: on-failure
  kpd-frontend:
    build: frontend/
    image: kupipodaridai-frontend
    container_name: kpd-frontend-cont
    ports:
      - "8081:80"
volumes:
  postgres-data: