services:
  app:
    build: backend/
    image: kupipodaridai-backend
    depends_on:
      - postgres
    ports: 
      - "3000:3000"
    links:
      - postgres:$POSTGRES_HOST
    env_file:
      - .env
    restart: on-failure
  postgres:
    image: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: on-failure
  frontend:
    build: frontend/
    image: kupipodaridai-frontend
    ports:
      - "3001:80"
    links:
      - app:backend.local
volumes:
  postgres-data: